### ISSUE TITLE
Create support documentation on recurring check-ins

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#213]
From tenfour-archive created by [Erioldoesdesign](https://github.com/Erioldoesdesign): ushahidi/tenfour-archive#1567  

Every time a feature goes live support documentation should be included as part of the dependancy for a feature to pass QA and get merged.

https://www.tenfour.org/support

Within the 'Check-ins' section, create a page/section that describes how recurring check-ins works, along with screenshots for the feature working. Like a step-by step.

A developer/QA team member should sign-off on the documentation to ensure that in the information is accurate.

**Comment by CeciliaHinga** [comment]
Full user documentation WIP is here via @CeciliaHinga : https://docs.google.com/document/d/1vsI1IIsphZAFyHRAhBw16BKpQnMfc12kAOpwO8ppSzA/edit?ts=5d2c933f#heading=h.7a646ca1tdyj

**Comment by Erioldoesdesign** [comment]
This was completed :) https://www.tenfour.org/support/compose-a-checkin
